const makeQuestion = (questionText, options, correctIndex, explanation) => ({
  questionText,
  options: {
    op1: options[0],
    op2: options[1],
    op3: options[2],
    op4: options[3],
  },
  correctAnswer: options[correctIndex],
  explanation,
});

const quizData = [
  {
    title: 'Mathematics Fundamentals',
    subject: 'Mathematics',
    imgUrl: '/quiz-images/mathematics.svg',
    category: 'Academic',
    difficulty: 'Intermediate',
    timeLimit: 12,
    questions: [
      makeQuestion('What is 15% of 200?', ['15', '20', '30', '40'], 2, '15/100 multiplied by 200 equals 30.'),
      makeQuestion('Solve: 3x + 5 = 20.', ['3', '5', '7', '15'], 1, 'Subtract 5, then divide 15 by 3 to get x = 5.'),
      makeQuestion('What is the area of a rectangle with length 8 cm and width 5 cm?', ['13 cm²', '26 cm²', '40 cm²', '80 cm²'], 2, 'Rectangle area is length multiplied by width: 8 × 5 = 40 cm².'),
      makeQuestion('Which fraction is equivalent to 0.75?', ['1/4', '1/2', '3/4', '4/3'], 2, '0.75 is 75/100, which simplifies to 3/4.'),
      makeQuestion('What is the square root of 144?', ['10', '11', '12', '14'], 2, '12 × 12 = 144.'),
      makeQuestion('A triangle has angles 50° and 60°. What is the third angle?', ['60°', '70°', '80°', '90°'], 1, 'Triangle angles total 180°, so 180 - 50 - 60 = 70°.'),
      makeQuestion('What is 2³ × 2²?', ['2⁵', '4⁵', '2⁶', '4⁶'], 0, 'When multiplying equal bases, add exponents: 2^(3+2) = 2⁵.'),
      makeQuestion('What is the mean of 4, 6, 8, and 10?', ['6', '7', '8', '9'], 1, 'Their sum is 28 and 28 ÷ 4 = 7.'),
      makeQuestion('Which number is prime?', ['21', '27', '29', '33'], 2, '29 has no positive divisors other than 1 and 29.'),
      makeQuestion('If a = 4 and b = 3, what is a² + b²?', ['7', '12', '25', '49'], 2, '4² + 3² = 16 + 9 = 25.'),
    ],
  },
  {
    title: 'Physics Essentials',
    subject: 'Physics',
    imgUrl: '/quiz-images/physics.svg',
    category: 'Science',
    difficulty: 'Intermediate',
    timeLimit: 12,
    questions: [
      makeQuestion('What is the SI unit of force?', ['Joule', 'Newton', 'Pascal', 'Watt'], 1, 'Force is measured in newtons (N).'),
      makeQuestion('Which formula represents speed?', ['Distance × time', 'Distance ÷ time', 'Time ÷ distance', 'Mass × acceleration'], 1, 'Speed is distance traveled divided by elapsed time.'),
      makeQuestion('What happens to an object at rest when the net force on it is zero?', ['It accelerates', 'It remains at rest', 'It loses mass', 'It gains energy'], 1, 'By Newton’s first law, zero net force means no change in motion.'),
      makeQuestion('Which type of energy is stored in a stretched spring?', ['Kinetic energy', 'Chemical energy', 'Elastic potential energy', 'Thermal energy'], 2, 'A deformed spring stores elastic potential energy.'),
      makeQuestion('Light travels fastest through which medium?', ['Vacuum', 'Water', 'Glass', 'Air'], 0, 'Light reaches its maximum speed in a vacuum.'),
      makeQuestion('What is the approximate acceleration due to gravity near Earth’s surface?', ['4.9 m/s²', '8.0 m/s²', '9.8 m/s²', '12.0 m/s²'], 2, 'Earth’s gravitational acceleration is approximately 9.8 m/s².'),
      makeQuestion('Which instrument measures electric current?', ['Voltmeter', 'Ammeter', 'Barometer', 'Thermometer'], 1, 'An ammeter measures current in amperes.'),
      makeQuestion('What is the unit of electrical resistance?', ['Volt', 'Ampere', 'Ohm', 'Coulomb'], 2, 'Electrical resistance is measured in ohms (Ω).'),
      makeQuestion('Which color of visible light has the longest wavelength?', ['Violet', 'Blue', 'Green', 'Red'], 3, 'Red has the longest wavelength in the visible spectrum.'),
      makeQuestion('A 2 kg object accelerates at 3 m/s². What force acts on it?', ['1.5 N', '5 N', '6 N', '9 N'], 2, 'F = ma = 2 × 3 = 6 N.'),
    ],
  },
  {
    title: 'Chemistry Basics',
    subject: 'Chemistry',
    imgUrl: '/quiz-images/chemistry.svg',
    category: 'Science',
    difficulty: 'Intermediate',
    timeLimit: 12,
    questions: [
      makeQuestion('What is the chemical symbol for sodium?', ['S', 'So', 'Na', 'N'], 2, 'Sodium’s symbol is Na, from the Latin name natrium.'),
      makeQuestion('Which particle has a negative charge?', ['Proton', 'Neutron', 'Electron', 'Nucleus'], 2, 'Electrons carry negative electric charge.'),
      makeQuestion('What is the pH of a neutral solution at room temperature?', ['0', '5', '7', '14'], 2, 'A neutral aqueous solution has pH 7 at room temperature.'),
      makeQuestion('Which gas is produced when an acid reacts with a carbonate?', ['Oxygen', 'Hydrogen', 'Carbon dioxide', 'Nitrogen'], 2, 'Acid-carbonate reactions release carbon dioxide.'),
      makeQuestion('What is H₂O commonly called?', ['Hydrogen peroxide', 'Water', 'Oxygen', 'Salt'], 1, 'H₂O is the molecular formula for water.'),
      makeQuestion('Which element has atomic number 6?', ['Carbon', 'Nitrogen', 'Oxygen', 'Boron'], 0, 'Carbon contains six protons and has atomic number 6.'),
      makeQuestion('What type of bond involves sharing electron pairs?', ['Ionic bond', 'Covalent bond', 'Metallic bond', 'Hydrogen bond'], 1, 'Covalent bonds form through shared electron pairs.'),
      makeQuestion('Which state of matter has a fixed volume but no fixed shape?', ['Solid', 'Liquid', 'Gas', 'Plasma'], 1, 'A liquid keeps its volume but takes the shape of its container.'),
      makeQuestion('What is the smallest unit of an element that retains its properties?', ['Molecule', 'Atom', 'Compound', 'Ion'], 1, 'An atom is the smallest characteristic unit of an element.'),
      makeQuestion('Which process changes a liquid into a gas at its surface?', ['Condensation', 'Freezing', 'Evaporation', 'Sublimation'], 2, 'Evaporation is vaporization occurring at a liquid’s surface.'),
    ],
  },
  {
    title: 'Biology Foundations',
    subject: 'Biology',
    imgUrl: '/quiz-images/biology.svg',
    category: 'Science',
    difficulty: 'Intermediate',
    timeLimit: 12,
    questions: [
      makeQuestion('What is the basic unit of life?', ['Tissue', 'Organ', 'Cell', 'Organism'], 2, 'All living organisms are made of one or more cells.'),
      makeQuestion('Which organelle is known as the powerhouse of the cell?', ['Nucleus', 'Mitochondrion', 'Ribosome', 'Vacuole'], 1, 'Mitochondria generate most cellular ATP.'),
      makeQuestion('Which pigment absorbs light for photosynthesis?', ['Hemoglobin', 'Melanin', 'Chlorophyll', 'Keratin'], 2, 'Chlorophyll captures light energy in plants.'),
      makeQuestion('What molecule carries genetic information?', ['ATP', 'DNA', 'Glucose', 'Protein'], 1, 'DNA stores hereditary information in most organisms.'),
      makeQuestion('Which human organ pumps blood?', ['Lung', 'Liver', 'Heart', 'Kidney'], 2, 'The heart pumps blood through the circulatory system.'),
      makeQuestion('What gas do plants absorb during photosynthesis?', ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], 2, 'Plants use carbon dioxide to produce glucose.'),
      makeQuestion('Which blood cells help defend the body against infection?', ['Red blood cells', 'White blood cells', 'Platelets', 'Plasma cells only'], 1, 'White blood cells are central to immune defense.'),
      makeQuestion('Where does most nutrient absorption occur in humans?', ['Stomach', 'Large intestine', 'Small intestine', 'Esophagus'], 2, 'The small intestine provides a large surface for nutrient absorption.'),
      makeQuestion('What is the process of cell division for growth and repair?', ['Meiosis', 'Mitosis', 'Respiration', 'Diffusion'], 1, 'Mitosis produces genetically similar body cells.'),
      makeQuestion('Which level of organization is made of similar cells working together?', ['Tissue', 'Organ', 'System', 'Organism'], 0, 'A tissue is a group of similar cells performing a shared function.'),
    ],
  },
  {
    title: 'English Language Skills',
    subject: 'English',
    imgUrl: '/quiz-images/english.svg',
    category: 'Language',
    difficulty: 'Intermediate',
    timeLimit: 10,
    questions: [
      makeQuestion('Which word is a synonym for “rapid”?', ['Slow', 'Quick', 'Quiet', 'Heavy'], 1, 'Rapid and quick both mean moving or happening fast.'),
      makeQuestion('Which sentence uses the apostrophe correctly?', ['The dogs bone was buried.', 'The dog’s bone was buried.', 'The dogs’ bone was buried for one dog.', 'The dogs bone’s was buried.'], 1, 'The singular possessive “dog’s” shows that the bone belongs to one dog.'),
      makeQuestion('Identify the adjective: “The bright sun warmed the beach.”', ['sun', 'warmed', 'bright', 'beach'], 2, '“Bright” describes the noun “sun.”'),
      makeQuestion('What is the past tense of “teach”?', ['teached', 'taught', 'teachen', 'teaching'], 1, '“Taught” is the irregular past tense of “teach.”'),
      makeQuestion('Which word is spelled correctly?', ['Definately', 'Definitely', 'Definetly', 'Definatly'], 1, '“Definitely” is the correct spelling.'),
      makeQuestion('Which sentence is in the passive voice?', ['Maya wrote the report.', 'The report was written by Maya.', 'Maya is writing the report.', 'Maya writes reports.'], 1, 'The subject “report” receives the action in the passive sentence.'),
      makeQuestion('What does the prefix “un-” usually mean?', ['again', 'before', 'not', 'many'], 2, 'The prefix “un-” commonly expresses negation or reversal.'),
      makeQuestion('Which punctuation mark ends a direct question?', ['Period', 'Comma', 'Colon', 'Question mark'], 3, 'A direct question normally ends with a question mark.'),
      makeQuestion('Choose the correct sentence.', ['They is going home.', 'They are going home.', 'They am going home.', 'They be going home.'], 1, 'The plural subject “they” takes the verb “are.”'),
      makeQuestion('Which word is an antonym of “ancient”?', ['Old', 'Historic', 'Modern', 'Ruined'], 2, 'Modern means current or recent, opposite to ancient.'),
    ],
  },
  {
    title: 'Computer Science Core',
    subject: 'Computer Science',
    imgUrl: '/quiz-images/computer-science.svg',
    category: 'Technology',
    difficulty: 'Intermediate',
    timeLimit: 12,
    questions: [
      makeQuestion('What does CPU stand for?', ['Central Processing Unit', 'Computer Personal Unit', 'Central Program Utility', 'Core Processing User'], 0, 'CPU stands for Central Processing Unit.'),
      makeQuestion('Which data structure follows First In, First Out?', ['Stack', 'Queue', 'Tree', 'Graph'], 1, 'A queue removes items in the order they were added.'),
      makeQuestion('Which binary value equals decimal 10?', ['1001', '1010', '1100', '1110'], 1, 'Binary 1010 equals 8 + 2 = 10.'),
      makeQuestion('What is the primary purpose of an operating system?', ['Create websites', 'Manage hardware and software resources', 'Compile only Java programs', 'Store data permanently without hardware'], 1, 'An operating system coordinates hardware, applications, files, and users.'),
      makeQuestion('Which protocol is commonly used to securely browse websites?', ['FTP', 'HTTP', 'HTTPS', 'SMTP'], 2, 'HTTPS encrypts HTTP traffic using TLS.'),
      makeQuestion('What does a database primary key do?', ['Encrypts every record', 'Uniquely identifies a record', 'Sorts all columns alphabetically', 'Deletes duplicate tables'], 1, 'A primary key uniquely identifies each row or document record.'),
      makeQuestion('Which programming construct repeats a block of code?', ['Variable', 'Loop', 'Comment', 'Constant'], 1, 'Loops repeat instructions while a condition or sequence applies.'),
      makeQuestion('What is the time complexity of binary search on a sorted array?', ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], 1, 'Binary search halves the search range each step, giving O(log n).'),
      makeQuestion('Which of these is a version control system?', ['Git', 'HTML', 'CSS', 'SQL'], 0, 'Git tracks changes and coordinates source code history.'),
      makeQuestion('What is an algorithm?', ['A physical computer part', 'A step-by-step procedure for solving a problem', 'A type of database table', 'A network cable standard'], 1, 'An algorithm is a finite sequence of steps used to solve a problem.'),
    ],
  },
  {
    title: 'Quantitative Aptitude Practice',
    subject: 'Quantitative Aptitude',
    imgUrl: '/quiz-images/quantitative-aptitude.svg',
    category: 'Aptitude',
    difficulty: 'Intermediate',
    timeLimit: 30,
    requiredQuestionCount: 25,
    questions: [
      makeQuestion('What is 25% of 480?', ['100', '120', '125', '140'], 1, '25% is one-fourth, and 480 divided by 4 is 120.'),
      makeQuestion('If the ratio of boys to girls is 3:5 and there are 40 students, how many are boys?', ['15', '18', '20', '25'], 0, 'There are 8 total ratio parts. Boys make up 3/8 of 40, which is 15.'),
      makeQuestion('A number increased by 20% becomes 360. What was the original number?', ['280', '300', '320', '340'], 1, 'The original number is 360 divided by 1.2, which equals 300.'),
      makeQuestion('What is the average of 12, 18, 24, 30, and 36?', ['22', '24', '26', '28'], 1, 'The sum is 120, and 120 divided by 5 is 24.'),
      makeQuestion('A train travels 240 km in 4 hours. What is its average speed?', ['50 km/h', '55 km/h', '60 km/h', '65 km/h'], 2, 'Average speed is distance divided by time: 240 divided by 4 equals 60 km/h.'),
      makeQuestion('What is the simple interest on Rs. 5,000 at 8% per year for 2 years?', ['Rs. 400', 'Rs. 600', 'Rs. 800', 'Rs. 1,000'], 2, 'Simple interest is PRT/100: 5000 x 8 x 2 / 100 = 800.'),
      makeQuestion('An item costs Rs. 800 and is sold for Rs. 920. What is the profit percentage?', ['12%', '15%', '18%', '20%'], 1, 'Profit is 120. The profit percentage is 120/800 x 100 = 15%.'),
      makeQuestion('A shop offers a 10% discount on an item marked Rs. 1,500. What is the selling price?', ['Rs. 1,300', 'Rs. 1,325', 'Rs. 1,350', 'Rs. 1,400'], 2, 'The discount is Rs. 150, so the selling price is Rs. 1,350.'),
      makeQuestion('If 8 workers complete a job in 15 days, how many days will 12 workers take at the same rate?', ['8 days', '10 days', '12 days', '18 days'], 1, 'Total work is 8 x 15 = 120 worker-days. 120 divided by 12 is 10 days.'),
      makeQuestion('A can complete a job in 12 days and B in 18 days. What fraction of the job do they complete together in one day?', ['1/5', '5/36', '1/6', '7/36'], 1, 'Their combined one-day work is 1/12 + 1/18 = 5/36.'),
      makeQuestion('A car covers half a journey at 40 km/h and the other half at 60 km/h. What is its average speed?', ['45 km/h', '48 km/h', '50 km/h', '52 km/h'], 1, 'For equal distances, average speed is 2ab/(a+b) = 48 km/h.'),
      makeQuestion('What is the least common multiple of 12 and 18?', ['24', '30', '36', '72'], 2, 'The smallest number divisible by both 12 and 18 is 36.'),
      makeQuestion('What is the highest common factor of 48 and 72?', ['12', '18', '24', '36'], 2, 'The greatest number that divides both 48 and 72 is 24.'),
      makeQuestion('If 3x - 7 = 20, what is x?', ['7', '8', '9', '10'], 2, 'Adding 7 gives 3x = 27, so x = 9.'),
      makeQuestion('The sum of two consecutive integers is 51. What is the smaller integer?', ['24', '25', '26', '27'], 1, 'The consecutive integers are 25 and 26.'),
      makeQuestion('What is the next number in the series 2, 6, 12, 20, 30, ...?', ['36', '40', '42', '44'], 2, 'The differences are 4, 6, 8, and 10; the next difference is 12, giving 42.'),
      makeQuestion('A father is three times as old as his son. Their ages total 48 years. How old is the son?', ['10 years', '12 years', '14 years', '16 years'], 1, 'Let the son be x. Then x + 3x = 48, so x = 12.'),
      makeQuestion('A mixture contains milk and water in the ratio 7:3. How much water is in 20 litres of the mixture?', ['4 litres', '6 litres', '8 litres', '14 litres'], 1, 'Water is 3/10 of 20 litres, which is 6 litres.'),
      makeQuestion('What is the probability of rolling an even number on a fair six-sided die?', ['1/3', '1/2', '2/3', '5/6'], 1, 'There are three even outcomes out of six, so the probability is 3/6 = 1/2.'),
      makeQuestion('A rectangular field is 25 m long and 16 m wide. What is its perimeter?', ['41 m', '80 m', '82 m', '400 m'], 2, 'Perimeter is 2 x (25 + 16) = 82 m.'),
      makeQuestion('What is the area of a circle with radius 7 cm, using pi = 22/7?', ['44 cm2', '88 cm2', '154 cm2', '308 cm2'], 2, 'Area is pi r squared: 22/7 x 7 x 7 = 154 cm2.'),
      makeQuestion('A sum doubles in 5 years at simple interest. What is the annual interest rate?', ['10%', '15%', '20%', '25%'], 2, 'To double, interest equals principal. Thus RT/100 = 1, so R = 100/5 = 20%.'),
      makeQuestion('If 15 pens cost Rs. 225, what is the cost of 8 pens?', ['Rs. 100', 'Rs. 110', 'Rs. 120', 'Rs. 135'], 2, 'One pen costs Rs. 15, so 8 pens cost Rs. 120.'),
      makeQuestion('In an election, a candidate receives 55% of 8,000 votes. How many votes did the candidate receive?', ['4,200', '4,400', '4,600', '4,800'], 1, '55% of 8,000 is 0.55 x 8,000 = 4,400.'),
      makeQuestion('The present ages of A and B are in the ratio 4:5. If B is 30 years old, how old is A?', ['20 years', '22 years', '24 years', '25 years'], 2, 'Five ratio parts equal 30, so one part is 6 and A is 4 x 6 = 24.'),
    ],
  },
];

module.exports = quizData;
